{
 "title": "Apps Portal Status",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CD3NCY | Apps Portal . Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Apps Portal $tag_site",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "site" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "aportal" }
     ]
    }
   ]
  },
  {
   "title": "CD3NCY | Apps Portal . Availability | AKAP Internal",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Apps Portal (internal) $tag_site",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "site" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apps-portal.server.usage",
     "select": [
      [
       { "params": [ "user-time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "host-name",
       "operator": "=",
       "value": "xusea2-akap-cd3ncy-2.nominum.cloud"
      }
     ]
    }
   ]
  },
  {
   "title": "CD3NCY  | Apps Portal . Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "US East 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "127.0.0.1" }
     ]
    },
    {
     "alias": "US WEST 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "https://127.0.0.1" }
     ]
    },
    {
     "alias": "Apps Portal Average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "server",
       "operator": "=~",
       "value": "/(18.223.104.153|13.57.133.34)/"
      }
     ]
    }
   ]
  },
  {
   "title": "CD3NCY | Apps Portal . Processes | US West 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Apps Portal Process ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nagios_state_nom-apps-portal_process",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "xuswe1-ap-cd3ncy-2.nominum.cloud"
      }
     ]
    }
   ]
  },
  {
   "title": "CD3NCY | Apps Portal . Processes | US East 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Apps Portal Process ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nagios_state_nom-sportal_process",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "xusea2-ap-cd3ncy-2.nominum.cloud"
      }
     ]
    }
   ]
  },
  {
   "title": "CD3NCY | Apps Portal . Heap Memory Used | US East 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host-name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apps-portal.server.usage",
     "select": [
      [
       { "params": [ "jvm.heap-used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "host-name",
       "operator": "=",
       "value": "xuswe1-ap-cd3ncy-2.nominum.cloud"
      }
     ]
    }
   ]
  },
  {
   "title": "CD3NCY | Apps Portal . Heap Memory Used | US East 2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host-name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apps-portal.server.usage",
     "select": [
      [
       { "params": [ "jvm.heap-used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "host-name",
       "operator": "=",
       "value": "xusea2-ap-cd3ncy-2.nominum.cloud"
      }
     ]
    }
   ]
  },
  {
   "title": "CD3NCY | Apps Portal . CPU Time (User & System) | US East 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host-name]] (system)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apps-portal.server.usage",
     "select": [
      [
       { "params": [ "system-time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "host-name",
       "operator": "=",
       "value": "xuswe1-ap-cd3ncy-2.nominum.cloud"
      }
     ]
    },
    {
     "alias": "[[tag_host-name]] (user)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apps-portal.server.usage",
     "select": [
      [
       { "params": [ "user-time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "host-name",
       "operator": "=",
       "value": "xuswe1-ap-cd3ncy-2.nominum.cloud"
      }
     ]
    }
   ]
  },
  {
   "title": "CD3NCY | Apps Portal . CPU Time (User & System) | US East 2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host-name]] (system)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apps-portal.server.usage",
     "select": [
      [
       { "params": [ "system-time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "host-name",
       "operator": "=",
       "value": "xusea2-akap-cd3ncy-2.nominum.cloud"
      }
     ]
    },
    {
     "alias": "[[tag_host-name]] (user)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apps-portal.server.usage",
     "select": [
      [
       { "params": [ "user-time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "host-name",
       "operator": "=",
       "value": "xusea2-ap-cd3ncy-2.nominum.cloud"
      }
     ]
    }
   ]
  }
 ]
}