influxdb:
  image: influxdb:1.7.6
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'

telegraf:
  image: telegraf:latest
  container_name: telegraf
  links:
    - influxdb

grafana:
  image: grafana/grafana:5.2.2
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
