apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
      - env:
        - name: INFLUXDB_DATA_ENGINE
          value: tsm1
        - name: INFLUXDB_REPORTING_DISABLED
          value: "false"
        image: influxdb:1.7.6
        name: influxdb
        ports:
        - containerPort: 8083
        - containerPort: 8086
        - containerPort: 8090
        resources: {}
      restartPolicy: Always
status: {}
