---
- name: create user of grafana
  user: name=grafana password=grafana

- name: download grafana from official site.
  get_url: url=https://dl.grafana.com/oss/release/grafana-{{ grafana.vars }}.linux-amd64.tar.gz 
           dest=/tmp/grafana-{{ grafana.vars }}.tar.gz

- name: mkdir of grafana
  file: state=directory
        path=/opt
        owner=grafana
        group=grafana

- name: unarchive of grafana
  unarchive: src=/tmp/grafana-{{ grafana.vars }}.tar.gz
             dest=/opt
             copy=no

- name: rename file of config.sample.js to the config.js
  template: src=config.js 
            dest=/opt/grafana-{{ grafana.vars }}/config.js 
            owner=grafana 
            group=grafana 
            mode=0644
  notify: restart nginx
