---
- name: get package of influxdb from official
  get_url: 
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.7.6_amd64.deb
    dest: /tmp/influxdb_latest_amd64.deb

- name: install deb package of influxdb from official
  shell: dpkg -i /tmp/influxdb_latest_amd64.deb
  when: ansible_distribution in ('Debian', 'Ubuntu')